server:
  port: 55555
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/supervisory
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
#  jpa:
#    database : MYSQL
#    show-sql : true
#    hibernate:
#      ddl-auto : update
#      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect : org.hibernate.dialect.MySQL5Dialect
  # 配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  #mvc:
   # static-path-pattern: /static/**

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.supervisory.base.model  # 注意：对应实体类的路径
